package com.rexo.mahi;
import android.app.*;import android.os.*;import android.content.*;import android.speech.*;import android.speech.tts.*;import android.view.*;import android.widget.*;import java.util.*;
public class MainActivity extends Activity implements TextToSpeech.OnInitListener{
 TextView status; EditText input; TextToSpeech tts; static final int REQ=9;
 public void onCreate(Bundle b){super.onCreate(b);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(32,48,32,32);TextView title=new TextView(this);title.setText("MAHI");title.setTextSize(32);l.addView(title);status=new TextView(this);status.setText("Ready • তোমার কথা বলো");status.setTextSize(18);l.addView(status);input=new EditText(this);input.setHint("মাহিকে কিছু বলো…");l.addView(input,new LinearLayout.LayoutParams(-1,0,1));Button ask=new Button(this);ask.setText("কথা বলো");ask.setOnClickListener(v->listen());l.addView(ask);Button send=new Button(this);send.setText("Send");send.setOnClickListener(v->reply(input.getText().toString()));l.addView(send);setContentView(l);tts=new TextToSpeech(this,this);}
 void listen(){status.setText("শুনছি…");Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"bn-BD");try{startActivityForResult(i,REQ);}catch(Exception e){status.setText("Speech recognition unavailable");}}
 protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==REQ&&c==RESULT_OK&&d!=null){ArrayList<String>a=d.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS);if(a!=null&&!a.isEmpty()){input.setText(a.get(0));reply(a.get(0));}}}
 void reply(String s){if(s==null||s.trim().isEmpty())return;String x=s.toLowerCase(Locale.ROOT);String out;if(x.contains("হাই")||x.contains("hello")||x.contains("হ্যালো"))out="হাই! আমি মাহি। বলো, কী করতে হবে?";else if(x.contains("কে")&&x.contains("মাহি"))out="আমি তোমার MAHI AI assistant।";else out="বুঝেছি। এই Alpha version-এ আমি তোমার কথা শুনে উত্তর দিচ্ছি।";status.setText(out);if(tts!=null)tts.speak(out,TextToSpeech.QUEUE_FLUSH,null,"mahi");}
 public void onInit(int s){if(s==TextToSpeech.SUCCESS)tts.setLanguage(new Locale("bn","BD"));}protected void onDestroy(){if(tts!=null){tts.stop();tts.shutdown();}super.onDestroy();}}
